#!/usr/bin/env python
import os

dirs = os.listdir('.')

for DIR in dirs:
    if not os.path.isdir(DIR):
        continue
    cpt = sum([len(files) for r, d, files in os.walk(DIR)])
    print "{0}: {1}".format(DIR, cpt)

