#! /bin/bash

# put it to /etc/init.d/testdaemon

service_name="testdaemon"
service_pidfile="/var/run/testdaemon.pid"
python="python"
program="/usr/share/testdaemon/testdaemon.py"

# ubuntu
# . /lib/lsb/init-functions

start() {
    if [ -e $service_pidfile ]; then
        ps -p `cat $service_pidfile` >/dev/null 2>&1
        ret=$?
    else
        ret=1
    fi
    if [ $ret = 0 ]; then
        echo "$service_name (`cat $service_pidfile`) is already running..."
        exit 1
    fi
    echo "Starting server"
    # Start the daemon
    $python $program start
    sleep 3 # in case the pid file is not generated
    ps -p `cat $service_pidfile >/dev/null 2>&1` >/dev/null 2>&1
    rc=$?
}

stop() {
    echo "Stopping server"
    # Stop the daemon
    $python $program stop
}

status() {
    #checkpid `cat $service_pidfile 2>/dev/null`
    if [ -e $service_pidfile ]; then
        ps -p `cat $service_pidfile` >/dev/null 2>&1
        ret=$?
    else
        ret=1
    fi
    if [ $ret = 0 ]; then
        echo "$service_name (`cat $service_pidfile`) is running"
    else
        echo "$service_name is not running"
    fi
}


case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
status)
    status
    ;;
*)
    echo "Usage: $0 {start|stop|restart|status}"
esac

exit 0


