#! /bin/bash

# put it to /etc/init.d/testdaemon

service_name="testdaemon"
service_pidfile="/var/run/testdaemon.pid"
python="python"
program="/usr/share/testdaemon/testdaemon.py"

case "$1" in
  start)
    echo "Starting server"
    # Start the daemon 
    $python $program start
    ;;
  stop)
    echo "Stopping server"
    # Stop the daemon
    $python $program stop
    ;;
  restart)
    echo "Restarting server"
    $python $program restart
    ;;
  status)
    #checkpid `cat $service_pidfile 2>/dev/null`
    ps -p `cat $service_pidfile` >/dev/null 2>&1
    ret=$?
    if [ $ret = 0 ]; then
        echo "$service_name (`cat $service_pidfile`) is running"
    else
        echo "$service_name does not exist"

    fi
    ;;
  *)
    # Refuse to do other stuff
    echo "Usage: /etc/init.d/testdaemon.sh {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0

